name: make-release
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - uses: actions/checkout@v2
      
      # Create dist directory
      - name: Create /dist
        run: mkdir dist

      # Build CSS
      - name: Sass Build
        uses: gha-utilities/sass-build@v0.4.8
        with:
          source: src/fluent-build.scss
          destination: dist/Fluent-Discord.css
          outputStyle: expanded
          
      # Delete @charset
      - name: Delete charset
        run: sed -i '1d' dist/Fluent-Discord.css

      # Deploy to gh-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
          keep_files: true
          commit_message: Deployment from Action
